# Generated by Django 3.1.12 on 2025-08-17 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '0001_initial'),
        ('utilizadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField(auto_now_add=True)),
                ('data_retirada', models.DateField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.livro')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilizadores.utilizadorbiblioteca')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
    ]
